### ISSUE TITLE
Unable to resolve twirl dependency

### ISSUE THREAD

**Issue by jdcohen220** [twitter/scala_school2#105]
When I clone the project and execute `sbt run` the following error is thrown from sbt:
```[error] Server access Error: Received fatal alert: internal_error url=https://repo.spray.io/io/spray/twirl-compiler_2.10/0.7.0/twirl-compiler_2.10-0.7.0.pom
[warn]  module not found: io.spray#twirl-compiler_2.10;0.7.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/io.spray/twirl-compiler_2.10/0.7.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/twirl-compiler_2.10/0.7.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/jasoncohen/.ivy2/local/io.spray/twirl-compiler_2.10/0.7.0/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/jasoncohen/.sbt/preloaded/io.spray/twirl-compiler_2.10/0.7.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/jasoncohen/.sbt/preloaded/io/spray/twirl-compiler_2.10/0.7.0/twirl-compiler_2.10-0.7.0.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/spray/twirl-compiler_2.10/0.7.0/twirl-compiler_2.10-0.7.0.pom
[warn] ==== spray repo: tried
[warn]   https://repo.spray.io/io/spray/twirl-compiler_2.10/0.7.0/twirl-compiler_2.10-0.7.0.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: io.spray#twirl-compiler_2.10;0.7.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          io.spray:twirl-compiler_2.10:0.7.0
[warn]            +- io.spray:sbt-twirl:0.7.0 (scalaVersion=2.10, sbtVersion=0.13) (/Users/jasoncohen/Documents/Intellij/scala_school2/project/plugins.sbt#L5-6)
[warn]            +- default:scala_school2-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: io.spray#twirl-compiler_2.10;0.7.0: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by jdcohen220** [comment]
FWIW Changing the protocol for the spray repo from `https` to `http` in `puglins.sbt` and `build.sbt` seemed to fix it.
